---
# tasks file for docker-jenkins

- name: Install docker
  yum:
    name: docker
    state: present
  become: yes

- name: Start Docker service
  service:
    name: docker
    state: started
    enabled: yes
  become: yes

- name: Set ec2-user to Docker group
  user:
    name: "{{ ruser }}"
    append: yes
    groups: docker
  become: yes

- name: Install python3 and modules
  yum:
    name: ['python3', 'python3-pip']
    state: present
    update_cache: yes
  become: yes

- name: Install Docker SDK for Python
  vars:
    ansible_python_interpreter: /usr/bin/python3
  pip:
    name: docker
    extra_args: --user

- name: Run Jenkins Docker container
  vars:
    ansible_python_interpreter: /usr/bin/python3
  community.docker.docker_container:
    name: myjenkins
    image: jenkins/jenkins
    container_default_behavior: compatibility
    ports:
      - "8080:8080"
    volumes:
      - jenkins-data:/var/jenkins_home
    networks:
      name: lab-net